### ISSUE TITLE
AttributeError: module 're' has no attribute 'Pattern'-python 3.6

### ISSUE THREAD

**Issue by monjoybme** [code-kage/tensorflow-builder#3]
Do you recommend Python 3.7 or higher for running Neural Studio?

**AttributeError: module 're' has no attribute 'Pattern'- python 3.6**

**Comment by monjoybme** [comment]
https://github.com/monjoybme/Neural-Studio/blob/dataset_as_graph/setup.py#L29

**Comment by angrybayblade** [comment]
type annotation has been fixed
